# Generated by Django 3.2.24 on 2024-03-05 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('region', '0001_initial'),
        ('reviews', '0001_initial'),
        ('itineraries', '0001_initial'),
        ('contacts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agent_bio_video', models.BooleanField(default=False)),
                ('verified_by_admin', models.BooleanField(null=True)),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov']), media.models.validate_video_size])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('video_duration', models.DurationField()),
                ('description', models.CharField(max_length=150)),
                ('agent_itineraries', models.ManyToManyField(blank=True, to='itineraries.AgentItinerary')),
                ('customer_itineraries', models.ManyToManyField(blank=True, to='itineraries.CustomerItinerary')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agent_bio_photo', models.BooleanField(default=False)),
                ('verified_by_admin', models.BooleanField(null=True)),
                ('image', models.ImageField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), media.models.validate_file_size])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image_size', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('agent_itineraries', models.ManyToManyField(blank=True, to='itineraries.AgentItinerary')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('customer_itineraries', models.ManyToManyField(blank=True, to='itineraries.CustomerItinerary')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('hotel_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelactivities')),
                ('itinerary_days', models.ManyToManyField(blank=True, to='itineraries.ItineraryDay')),
                ('itinerary_groups', models.ManyToManyField(blank=True, to='itineraries.ItineraryGroup')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
