# Generated by Django 3.2.24 on 2024-03-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='photos/full/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='photos/medium/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/'),
        ),
    ]
