# Generated by Django 5.0.3 on 2024-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20240316_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='primary_image',
            field=models.BooleanField(default=False),
        ),
    ]
