# Generated by Django 3.2.24 on 2024-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_photo_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='primary_photo',
            field=models.BooleanField(default=False),
        ),
    ]
