# Generated by Django 4.2.10 on 2024-08-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_type_and_more'),
        ('region', '0005_regionsubsection'),
        ('contacts', '0007_alter_contact_categories_and_more'),
        ('reviews', '0002_auto_20240725_0641'),
        ('media', '0005_remove_photo_category_photo_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploaded_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.region'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
