
services:
  web:
    build: ./itins
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./itins:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      -   DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - DATABASE_URL=postgres://your_db_user:your_db_password@db:5432/your_db_name
    networks:
      - app-network

  frontend:
    build: ./frontend
    command: npm run dev
    # command: sh -c "npm install @radix-ui/react-switch npm rebuild rollup && npm run dev" 
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgis/postgis:14-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: