# Generated by Django 5.0.3 on 2024-04-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='sustainability_practices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
