# Generated by Django 5.0.3 on 2024-04-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_agentprofile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='short_bio',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
    ]
