# Generated by Django 3.2.24 on 2024-07-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_regionsubsection'),
        ('customers', '0005_agentprofile_business_name_agentprofile_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region'),
        ),
    ]
