# Generated by Django 4.2.10 on 2024-07-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='expertise_category',
            new_name='expertise_categories',
        ),
    ]
