# Generated by Django 4.2.10 on 2024-08-04 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_expertise_category_agentprofile_expertise_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_bio', models.TextField(blank=True, max_length=155, null=True)),
                ('bio', models.TextField(blank=True, max_length=450, null=True)),
                ('business_name', models.CharField(blank=True, max_length=55, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('sustainability_practices', models.TextField(blank=True, null=True)),
                ('hotel_owner', models.BooleanField(default=False)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('agent_starting_date', models.DateField(blank=True, null=True)),
                ('admin_description', models.TextField(blank=True, max_length=450, null=True)),
                ('default_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('default_organisation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('accompanying_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.potentialagent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_bio', models.TextField(blank=True, max_length=155, null=True)),
                ('bio', models.TextField(blank=True, max_length=450, null=True)),
                ('business_name', models.CharField(blank=True, max_length=55, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('sustainability_practices', models.TextField(blank=True, null=True)),
                ('hotel_owner', models.BooleanField(default=False)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('agent_starting_date', models.DateField(blank=True, null=True)),
                ('admin_description', models.TextField(blank=True, max_length=450, null=True)),
                ('default_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('default_organisation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accompanying_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.useragent')),
                ('expertise_categories', models.ManyToManyField(blank=True, to='customers.expertisecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
        migrations.AddField(
            model_name='useragent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='potentialagent',
            name='converted_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='potentialagent',
            name='expertise_categories',
            field=models.ManyToManyField(blank=True, to='customers.expertisecategory'),
        ),
        migrations.AddField(
            model_name='potentialagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_agent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
