# Generated by Django 4.2.10 on 2024-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_potentialagent_accompanying_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialagent',
            name='admin_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potentialagent',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potentialagent',
            name='expertise_categories',
            field=models.ManyToManyField(blank=True, null=True, to='customers.expertisecategory'),
        ),
    ]
