# Generated by Django 4.2.10 on 2024-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_potentialagent_admin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialagent',
            name='expertise_categories',
            field=models.ManyToManyField(blank=True, to='customers.expertisecategory'),
        ),
    ]
