# Generated by Django 4.2.9 on 2024-01-08 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('customers', '0001_initial'),
        ('region', '0001_initial'),
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('culinary', 'Culinary'), ('wildlife', 'Wildlife'), ('adventure', 'Adventure'), ('trekking', 'Trekking'), ('history', 'Historic'), ('cultural', 'Cultural'), ('motorbiking', 'Motorbiking'), ('fishing', 'Fishing')], max_length=100)),
                ('customisable', models.BooleanField(default=False)),
                ('cost_for_1_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_for_2_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_for_3_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_for_4_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('with_leader_cost_for_1_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('with_leader_cost_for_2_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('with_leader_cost_for_3_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('with_leader_cost_for_4_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visible_description', models.TextField(blank=True, max_length=800, null=True)),
                ('price_breakdown', models.BooleanField(default=False)),
                ('january_rating', models.IntegerField(default=0)),
                ('february_rating', models.IntegerField(default=0)),
                ('march_rating', models.IntegerField(default=0)),
                ('april_rating', models.IntegerField(default=0)),
                ('may_rating', models.IntegerField(default=0)),
                ('june_rating', models.IntegerField(default=0)),
                ('july_rating', models.IntegerField(default=0)),
                ('august_rating', models.IntegerField(default=0)),
                ('september_rating', models.IntegerField(default=0)),
                ('october_rating', models.IntegerField(default=0)),
                ('november_rating', models.IntegerField(default=0)),
                ('december_rating', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_itineraries', to='customers.agent')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_experts', to='customers.agent')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_notes', models.TextField(blank=True, max_length=800, null=True)),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children_6_to_12', models.IntegerField()),
                ('number_of_infants_0_to_5', models.IntegerField(default=0)),
                ('number_of_taxis', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('agent_listed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='customers.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_experts', to='customers.agent')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('original_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.agentitinerary')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mandatory_guide', models.BooleanField(default=False)),
                ('override_cost_for_1_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_2_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_3_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_4_pax', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('price_visible', models.BooleanField(default=True)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mandatory_guide', models.BooleanField(default=False)),
                ('mandatory_position_in_itinerary', models.IntegerField(default=0)),
                ('override_cost_for_1_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_2_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_3_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_4_pax', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=350)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_in_room', models.IntegerField(default=2)),
                ('children_in_room', models.IntegerField(default=0)),
                ('infants_in_room', models.IntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('customer_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_specifications', to='itineraries.customeritinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_note', models.TextField()),
                ('price_visible', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_price_markup_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraryday')),
            ],
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='itinerary_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerarygroup'),
        ),
        migrations.CreateModel(
            name='ItineraryGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_guide', models.BooleanField(default=False)),
                ('random_guide', models.BooleanField(default=False)),
                ('guide_price_override', models.IntegerField(blank=True, null=True)),
                ('mandatory_position_in_itinerary', models.IntegerField(default=0)),
                ('override_cost_for_1_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_2_pax', models.IntegerField(blank=True, null=True)),
                ('override_cost_for_3_pax', models.IntegerField(blank=True, null=True)),
                ('price_visible', models.BooleanField(default=True)),
                ('override_cost_for_4_pax', models.IntegerField(blank=True, null=True)),
                ('agent_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.agentitinerary')),
                ('customer_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.customeritinerary')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerarygroup')),
            ],
            options={
                'unique_together': {('agent_itinerary', 'group')},
            },
        ),
    ]
