# Generated by Django 4.2.9 on 2024-01-13 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCustomerParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='joined_group_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='fixed_group',
            field=models.BooleanField(default=False, help_text='Is this a fixed group itinerary?'),
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='group_start_date',
            field=models.DateField(blank=True, help_text='Start date for the group itinerary.', null=True),
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='max_group_size',
            field=models.IntegerField(blank=True, help_text='Maximum number of guests for the group.', null=True),
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='min_group_size',
            field=models.IntegerField(blank=True, help_text='Minimum number of guests for the group.', null=True),
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='non_customer_participants',
            field=models.ManyToManyField(blank=True, to='itineraries.noncustomerparticipant'),
        ),
    ]
