# Generated by Django 4.2.9 on 2024-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_noncustomerparticipant_agentitinerary_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarydaycomponent',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('contacted', 'Contacted'), ('not contacted', 'Not Contacted')], default='not contacted', max_length=100),
        ),
        migrations.AddField(
            model_name='itinerarydaycomponent',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
