# Generated by Django 5.0.3 on 2024-07-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('itineraries', '0002_alter_agentitinerary_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentitinerary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag'),
        ),
        migrations.AddField(
            model_name='agentitinerary',
            name='type',
            field=models.CharField(choices=[('hiking', 'Hiking'), ('fishing', 'Fishing'), ('cultural', 'Cultural'), ('cuisine', 'Cuisine')], default='hi', max_length=20),
            preserve_default=False,
        ),
    ]
