# Generated by Django 3.2.24 on 2024-07-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_agentitinerary_tags_agentitinerary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentitinerary',
            name='category',
        ),
    ]
