# Generated by Django 3.2.24 on 2024-07-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_remove_agentitinerary_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentitinerary',
            old_name='type',
            new_name='category',
        ),
    ]
