# Generated by Django 3.2.24 on 2024-07-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_rename_type_agentitinerary_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentitinerary',
            old_name='category',
            new_name='type',
        ),
    ]
