# Generated by Django 4.2.9 on 2024-01-08 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('region', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('platform_hotel', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('min_price_in_INR', models.DecimalField(decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('room_description', models.CharField(max_length=100)),
                ('room_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paytm', 'PayTM'), ('gpay', 'Gpay'), ('upi', 'UPI'), ('net_transfer', 'Net Transfer'), ('cash', 'Cash'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'Amex')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentHotel',
            fields=[
                ('hotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotels.hotel')),
                ('tac_percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage for this hotel', max_digits=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_hotels', to='customers.agent')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('parent_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_hotels', to='hotels.hotel')),
            ],
            bases=('hotels.hotel',),
        ),
        migrations.CreateModel(
            name='CustomizedHotel',
            fields=[
                ('hotel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotels.hotel')),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('private_info', models.CharField(blank=True, max_length=155, null=True)),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_customized_hotels', to='customers.agent')),
                ('payment_types', models.ManyToManyField(blank=True, to='hotels.paymenttype')),
            ],
            bases=('hotels.hotel',),
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.CharField(choices=[('EP', 'European Plan - No meals'), ('CP', 'Continental Plan - With breakfast'), ('MAP', 'Modified American Plan - With breakfast and dinner'), ('AP', 'American Plan - With all meals')], max_length=100)),
                ('rack_price_1p', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_price_2p', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_price_3p', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_price_2p_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_price_4p', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_price_3p_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack_price_4p_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overridden_net_price_1p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_net_price_2p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_net_price_3p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_net_price_2p_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_net_price_4p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_net_price_3p_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overridden_net_price_4p_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_for_customer_1p', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rate_for_customer_2p', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rate_for_customer_3p', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rate_for_customer_2p_child', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rate_for_customer_4p', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rate_for_customer_3p_child', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rate_for_customer_4p_child', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.agent')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom')),
            ],
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='agent_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_hotel_rooms', to='hotels.agenthotel'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='customized_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_rooms', to='hotels.customizedhotel'),
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(help_text='Check-in time')),
                ('check_out_time', models.TimeField(help_text='Check-out time')),
                ('zero_refund_days', models.IntegerField(blank=True, default=0, null=True)),
                ('quarter_refund_days', models.IntegerField(blank=True, default=0, null=True)),
                ('half_refund_days', models.IntegerField(blank=True, default=0, null=True)),
                ('percentage_deposit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('customized_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_info', to='hotels.customizedhotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('onsite_activity', models.BooleanField(default=False)),
                ('free_activity', models.BooleanField(default=False)),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom')),
                ('customized_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_amenities', to='hotels.customizedhotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('onsite_activity', models.BooleanField(default=False)),
                ('free_activity', models.BooleanField(default=False)),
                ('customized_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_activities', to='hotels.customizedhotel')),
            ],
        ),
    ]
