# Generated by Django 3.2.24 on 2024-07-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_tags_hotel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='type',
            new_name='payment_type',
        ),
    ]
