# Generated by Django 4.2.9 on 2024-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelactivities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedhotel',
            name='serves_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelactivities',
            name='can_be_personalised',
            field=models.BooleanField(default=False),
        ),
    ]
