# Generated by Django 3.2.24 on 2024-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_type_paymenttype_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('farmstay', 'Farmstay'), ('heritage', 'Heritage'), ('beach', 'Beach'), ('jungle', 'Wildlife and Jungle Lodges'), ('luxury', 'Luxury'), ('private villas', 'Private Villas'), ('wellness retreats', 'Wellness Retreats'), ('mountain stays', 'Mountain Stays'), ('hiking lodge', 'Hiking Lodge')], max_length=20),
        ),
    ]
