# Generated by Django 3.2.24 on 2024-07-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_regionsubsection'),
        ('hotels', '0004_alter_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='region_subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.regionsubsection'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('farmstay', 'Farmstay'), ('beach', 'Beach'), ('jungle', 'Wildlife and Jungle Lodges'), ('private villas', 'Private Villas'), ('wellness retreats', 'Wellness Retreats'), ('mountain stays', 'Mountain Stays'), ('hiking lodge', 'Hiking Lodge')], max_length=20),
        ),
    ]
