# Generated by Django 3.2.24 on 2024-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20240724_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='booking_com_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tripadvisor_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
