# Generated by Django 3.2.24 on 2024-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20240725_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedhotel',
            name='instagram_link',
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
