# Generated by Django 3.2.24 on 2024-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20240725_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_size_sq_ft',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_description',
            field=models.CharField(max_length=255),
        ),
    ]
