# Generated by Django 3.2.24 on 2024-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20240725_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_size_sq_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
