# Generated by Django 3.2.24 on 2024-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_hotelroom_room_size_sq_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_description',
            field=models.CharField(max_length=500),
        ),
    ]
