# Generated by Django 3.2.24 on 2024-07-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotelroom_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_description',
            field=models.CharField(max_length=555),
        ),
    ]
