# Generated by Django 3.2.24 on 2024-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('farmstay', 'Farmstay'), ('beach', 'Beach'), ('jungle', 'Wildlife and Jungle Lodges'), ('private villas', 'Private Villas'), ('wellness retreats', 'Wellness Retreats'), ('mountain stays', 'Mountain Stays'), ('hiking lodge', 'Hiking Lodge')], max_length=100),
        ),
    ]
