# Generated by Django 4.2.10 on 2024-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_auto_20240726_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedhotel',
            name='hotel_owner_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('founder', 'Founder')], max_length=20, null=True, unique=True),
        ),
    ]
