# Generated by Django 4.2.10 on 2024-08-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_customizedhotel_hotel_owner_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='email_address',
            new_name='email',
        ),
    ]
