# Generated by Django 3.2.24 on 2024-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('january_min_temperature', models.IntegerField(default=0)),
                ('february_min_temperature', models.IntegerField(default=0)),
                ('march_min_temperature', models.IntegerField(default=0)),
                ('april_min_temperature', models.IntegerField(default=0)),
                ('may_min_temperature', models.IntegerField(default=0)),
                ('june_min_temperature', models.IntegerField(default=0)),
                ('july_min_temperature', models.IntegerField(default=0)),
                ('august_min_temperature', models.IntegerField(default=0)),
                ('september_min_temperature', models.IntegerField(default=0)),
                ('october_min_temperature', models.IntegerField(default=0)),
                ('november_min_temperature', models.IntegerField(default=0)),
                ('december_min_temperature', models.IntegerField(default=0)),
                ('january_max_temperature', models.IntegerField(default=0)),
                ('february_max_temperature', models.IntegerField(default=0)),
                ('march_max_temperature', models.IntegerField(default=0)),
                ('april_max_temperature', models.IntegerField(default=0)),
                ('may_max_temperature', models.IntegerField(default=0)),
                ('june_max_temperature', models.IntegerField(default=0)),
                ('july_max_temperature', models.IntegerField(default=0)),
                ('august_max_temperature', models.IntegerField(default=0)),
                ('september_max_temperature', models.IntegerField(default=0)),
                ('october_max_temperature', models.IntegerField(default=0)),
                ('november_max_temperature', models.IntegerField(default=0)),
                ('december_max_temperature', models.IntegerField(default=0)),
                ('january_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('february_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('march_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('april_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('may_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('june_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('july_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('august_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('september_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('october_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('november_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
                ('december_weather', models.CharField(choices=[('sunny', 'Sunny'), ('sunny_and_cloudy', 'Sunny and Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('monsoon_rain', 'Monsoon Rain'), ('snow', 'Snow')], max_length=50)),
            ],
        ),
    ]
