# Generated by Django 5.0.3 on 2024-03-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_shortkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='shortkey',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
