# Generated by Django 3.2.24 on 2024-07-19 06:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_region_name_alter_region_shortkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='best_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='region',
            name='best_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
