# Generated by Django 3.2.24 on 2024-03-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_reference', models.CharField(max_length=255)),
                ('place_name', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
                ('ordering', models.PositiveIntegerField()),
                ('agent_itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itineraries.agentitinerary')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('itinerary_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraryday')),
                ('itinerary_day_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerarydaycomponent')),
            ],
        ),
    ]
