# Generated by Django 5.0.3 on 2024-07-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_tags_hotel_type'),
        ('waypoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel'),
        ),
    ]
