# Generated by Django 4.2.9 on 2024-01-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_for_1_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_for_2_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_for_3_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_for_4_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_1_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_2_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_3_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_4_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_fixed_price_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_fixed_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deletable', models.BooleanField(default=True)),
            ],
        ),
    ]
