# Generated by Django 3.2.24 on 2024-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('wheelchair_accessible', models.BooleanField(default=True)),
                ('age_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('fitness_level', models.CharField(choices=[('all', 'All'), ('ironman', 'Ironman'), ('tough', 'Tough'), ('challenging', 'Challenging'), ('moderate', 'moderate'), ('easy', 'Easy')], default='all', max_length=30)),
                ('price_for_1_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_for_2_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_for_3_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_for_4_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_1_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_2_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_3_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price_for_4_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_fixed_price_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_fixed_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deletable', models.BooleanField(default=True)),
            ],
        ),
    ]
