# Generated by Django 4.2.9 on 2024-01-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('hotels', '0001_initial'),
        ('components', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.agent'),
        ),
        migrations.AddField(
            model_name='component',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.agent'),
        ),
        migrations.AddField(
            model_name='component',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='component',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotelroom'),
        ),
    ]
