# Generated by Django 4.2.10 on 2024-08-07 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.componenttype'),
        ),
        migrations.AddField(
            model_name='component',
            name='is_platform_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='is_visible_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component',
            name='fitness_level',
            field=models.CharField(choices=[('all', 'All'), ('ironman', 'Ironman'), ('tough', 'Tough'), ('challenging', 'Challenging'), ('moderate', 'Moderate'), ('easy', 'Easy')], default='all', max_length=30),
        ),
    ]
