# Generated by Django 4.2.9 on 2024-01-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='age_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='fitness_level',
            field=models.CharField(choices=[('all', 'All'), ('ironman', 'Ironman'), ('tough', 'Tough'), ('challenging', 'Challenging'), ('moderate', 'moderate'), ('easy', 'Easy')], default='all', max_length=30),
        ),
        migrations.AddField(
            model_name='component',
            name='wheelchair_accessible',
            field=models.BooleanField(default=True),
        ),
    ]
