# Generated by Django 4.2.9 on 2024-01-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcategory',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.agent'),
        ),
        migrations.AddField(
            model_name='contactbusiness',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.agent'),
        ),
        migrations.AddField(
            model_name='contact',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.agent'),
        ),
        migrations.AddField(
            model_name='contact',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactbusiness'),
        ),
        migrations.AddField(
            model_name='contact',
            name='categories',
            field=models.ManyToManyField(to='contacts.contactcategory'),
        ),
    ]
