# Generated by Django 4.2.10 on 2024-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_visible_to_others',
            field=models.BooleanField(default=False),
        ),
    ]
