# Generated by Django 4.2.10 on 2024-08-08 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_alter_contact_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbusiness',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactbusiness',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactbusiness',
            name='business_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactbusiness',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
