# Generated by Django 4.2.10 on 2024-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contactbusiness_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.contactcategory'),
        ),
    ]
