# Generated by Django 4.2.10 on 2024-08-08 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='categories',
            field=models.ManyToManyField(blank=True, to='contacts.contactcategory'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='daily_rate_where_appropriate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
